In [2]:
#import imblearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
# To ignore all warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler


from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report


heart_disease = pd.read_csv(r"C:\Users\User\Desktop\iRonhack\Classes at Iron\Week 5\Day 1\lab-predictions-logistic-regression\data\framingham.csv")

In [3]:
heart_disease

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

# Standartization 

In [6]:
cols = []

for i in range(len(heart_disease.columns)):
    cols.append(heart_disease.columns[i].lower().replace(' ', '_'))
cols

heart_disease.columns = cols
heart_disease.columns


Index(['male', 'age', 'education', 'currentsmoker', 'cigsperday', 'bpmeds',
       'prevalentstroke', 'prevalenthyp', 'diabetes', 'totchol', 'sysbp',
       'diabp', 'bmi', 'heartrate', 'glucose', 'tenyearchd'],
      dtype='object')

# Cleaning the data

In [ ]:
# deleting the NaN values

In [9]:
heart_disease.isnull().sum()

male                 0
age                  0
education          105
currentsmoker        0
cigsperday          29
bpmeds              53
prevalentstroke      0
prevalenthyp         0
diabetes             0
totchol             50
sysbp                0
diabp                0
bmi                 19
heartrate            1
glucose            388
tenyearchd           0
dtype: int64

In [10]:
heart_disease_cleaned = heart_disease.dropna()

In [11]:
heart_disease_cleaned.isnull().sum()

male               0
age                0
education          0
currentsmoker      0
cigsperday         0
bpmeds             0
prevalentstroke    0
prevalenthyp       0
diabetes           0
totchol            0
sysbp              0
diabp              0
bmi                0
heartrate          0
glucose            0
tenyearchd         0
dtype: int64

In [17]:
heart_disease_cleaned.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
4231    False
4232    False
4233    False
4234    False
4237    False
Length: 3656, dtype: bool

In [19]:
print(heart_disease_cleaned.duplicated().sum())
print(heart_disease_cleaned.duplicated().value_counts())

0
False    3656
Name: count, dtype: int64


In [20]:
heart_disease_cleaned.groupby('tenyearchd').count()

male   age  education  currentsmoker  cigsperday  bpmeds  \
tenyearchd                                                             
0           3099  3099       3099           3099        3099    3099   
1            557   557        557            557         557     557   

            prevalentstroke  prevalenthyp  diabetes  totchol  sysbp  diabp  \
tenyearchd                                                                   
0                      3099          3099      3099     3099   3099   3099   
1                       557           557       557      557    557    557   

             bmi  heartrate  glucose  
tenyearchd                            
0           3099       3099     3099  
1            557        557      557

# Building a Logistic Regression

In [21]:

X = heart_disease_cleaned.drop('tenyearchd',axis = 1)
y = heart_disease_cleaned['tenyearchd']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size = 0.2)

LR = LogisticRegression()
LR.fit(X_train, y_train)

LR.score(X_test, y_test)

0.8346994535519126

In [29]:
LR.score(X_train, y_train)

0.8546511627906976

In [30]:
LR.score(X_test, y_test)

0.8346994535519126

# Prediction

In [63]:

pred = LR.predict(X_test)
pred


print("precision: ",precision_score(y_test,pred))
print("recall: ",recall_score(y_test,pred))
print("f1: ",f1_score(y_test,pred))




precision:  0.5333333333333333
recall:  0.06557377049180328
f1:  0.11678832116788322


In [64]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.84      0.99      0.91       610
           1       0.53      0.07      0.12       122

    accuracy                           0.83       732
   macro avg       0.69      0.53      0.51       732
weighted avg       0.79      0.83      0.78       732



In [65]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,pred)

array([[603,   7],
       [114,   8]], dtype=int64)

In [70]:
# to predict the probabilities instead of a class
predicted_probabilities = LR.predict_proba(X_test)[:,1]
#predicted_probabilities


In [69]:

# Then you need to define it by hand
custom_threshold = 0.2  # For example, use a threshold of 0.7
custom_predictions = (predicted_probabilities >= custom_threshold).astype(int)
#custom_predictions

In [71]:

pred = LR.predict(X_test)
pred


print("precision: ",precision_score(y_test,custom_predictions))
print("recall: ",recall_score(y_test,custom_predictions))
print("f1: ",f1_score(y_test,custom_predictions))



precision:  0.29239766081871343
recall:  0.4098360655737705
f1:  0.3412969283276451


In [72]:
confusion_matrix(y_test, custom_predictions)

array([[489, 121],
       [ 72,  50]], dtype=int64)

In [73]:
print(classification_report(y_test, custom_predictions))

              precision    recall  f1-score   support

           0       0.87      0.80      0.84       610
           1       0.29      0.41      0.34       122

    accuracy                           0.74       732
   macro avg       0.58      0.61      0.59       732
weighted avg       0.78      0.74      0.75       732



In [78]:
from sklearn.utils import resample

In [74]:
# oversampling / undersampling is only to be done on the TRAINING set
# our test set still must reflect reality!
train = pd.concat([X_train, y_train],axis=1)
display(train.shape)
train.head()

(2924, 16)

male  age  education  currentsmoker  cigsperday  bpmeds  \
780      0   46        3.0              1        20.0     0.0   
2218     1   43        2.0              1        20.0     0.0   
3251     0   48        3.0              1        20.0     0.0   
3482     1   38        2.0              0         0.0     0.0   
2662     0   51        1.0              0         0.0     0.0   

      prevalentstroke  prevalenthyp  diabetes  totchol  sysbp  diabp    bmi  \
780                 0             0         0    253.0  118.0   82.0  19.70   
2218                0             0         0    226.0  132.5   85.0  26.64   
3251                0             0         0    259.0  129.0   81.0  21.08   
3482                0             1         0    256.0  123.0   92.0  25.42   
2662                0             1         0    285.0  151.5   79.0  26.91   

      heartrate  glucose  tenyearchd  
780       100.0     70.0           0  
2218       72.0     58.0           0  
3251       75.0     65.0           0  
3482       62.0     82.0           0  
2662       84.0     76.0           0

In [76]:
# separate majority/minority classes
no_chd = train[train['tenyearchd']==0]
yes_chd = train[train['tenyearchd']==1]

display(no_chd .shape)
display(yes_chd.shape)

(2489, 16)

(435, 16)

In [79]:
# oversample minority
yes_chd_oversampled = resample(yes_chd, #<- oversample from here 
                                    replace=True, #<- we need replacement, since we don't have enough data otherwise
                                    n_samples = len(no_chd),#<- make both sets the same size # make the diabetes set equal to the size of no_diabetes
                                    random_state=0)

# both sets are now of a reasonable size
display(no_chd.shape)
display(yes_chd_oversampled.shape)

(2489, 16)

(2489, 16)

In [80]:
# Create an oversample dataframe
train_oversampled = pd.concat([no_chd,yes_chd_oversampled])
train_oversampled.head()

male  age  education  currentsmoker  cigsperday  bpmeds  \
780      0   46        3.0              1        20.0     0.0   
2218     1   43        2.0              1        20.0     0.0   
3251     0   48        3.0              1        20.0     0.0   
3482     1   38        2.0              0         0.0     0.0   
2662     0   51        1.0              0         0.0     0.0   

      prevalentstroke  prevalenthyp  diabetes  totchol  sysbp  diabp    bmi  \
780                 0             0         0    253.0  118.0   82.0  19.70   
2218                0             0         0    226.0  132.5   85.0  26.64   
3251                0             0         0    259.0  129.0   81.0  21.08   
3482                0             1         0    256.0  123.0   92.0  25.42   
2662                0             1         0    285.0  151.5   79.0  26.91   

      heartrate  glucose  tenyearchd  
780       100.0     70.0           0  
2218       72.0     58.0           0  
3251       75.0     65.0           0  
3482       62.0     82.0           0  
2662       84.0     76.0           0

In [82]:
y_train_over = train_oversampled['tenyearchd']
X_train_over = train_oversampled.drop('tenyearchd',axis = 1)

In [83]:
# Our Logistic Regression, while still not amazing, has improved substantially!
# especially at detecting instances of diabetes
LR = LogisticRegression(max_iter = 1000)
LR.fit(X_train_over, y_train_over)
pred = LR.predict(X_test)

print("Accuracy: ",LR.score(X_test, y_test))

print("precision: ",precision_score(y_test,pred))
print("recall: ",recall_score(y_test,pred))
print("f1: ",f1_score(y_test,pred))

print(classification_report(y_test, pred))

Accuracy:  0.6775956284153005
precision:  0.2857142857142857
recall:  0.6229508196721312
f1:  0.3917525773195876
              precision    recall  f1-score   support

           0       0.90      0.69      0.78       610
           1       0.29      0.62      0.39       122

    accuracy                           0.68       732
   macro avg       0.59      0.66      0.59       732
weighted avg       0.80      0.68      0.72       732



In [84]:
confusion_matrix(y_test,pred)

array([[420, 190],
       [ 46,  76]], dtype=int64)